#define IS_KEY_RELEASE(b) ((b) & KB_RELEASE_BASE)
#define MASK_RELEASE(b) ((b) & ~KB_RELEASE_BASE)
#define KB_RELEASE_BASE 0x80
#define KB_KC_SPECIAL_BASE KB_RELEASE_BASE
#define KB_KC_NULL 0x0
#define KB_KC_ERROR (KB_KC_SPECIAL_BASE + 0x0)
#define KB_KC_LSHIFT (KB_KC_SPECIAL_BASE + 0x1)
#define KB_KC_RSHIFT (KB_KC_SPECIAL_BASE + 0x2)
#define KB_KC_NUMLOCK (KB_KC_SPECIAL_BASE + 0x3)
#define KB_KC_SCROLLLOCK (KB_KC_SPECIAL_BASE + 0x4)
#define KB_KC_HOME (KB_KC_SPECIAL_BASE + 0x5)
#define KB_KC_UP (KB_KC_SPECIAL_BASE + 0x6)
#define KB_KC_PGUP (KB_KC_SPECIAL_BASE + 0x7)
#define KB_KC_MINUS (KB_KC_SPECIAL_BASE + 0x8)
#define KB_KC_LEFT (KB_KC_SPECIAL_BASE + 0x9)
#define KB_KC_RIGHT (KB_KC_SPECIAL_BASE + 0xA)
#define KB_KC_END (KB_KC_SPECIAL_BASE + 0xB)
#define KB_KC_DOWN (KB_KC_SPECIAL_BASE + 0xC)
#define KB_KC_PGDN (KB_KC_SPECIAL_BASE + 0xD)
#define KB_KC_INS (KB_KC_SPECIAL_BASE + 0xE)
#define KB_KC_DEL (KB_KC_SPECIAL_BASE + 0xF)
#define KB_KC_SYSRQ (KB_KC_SPECIAL_BASE + 0x10)
#define KB_KC_UNLABELLED (KB_KC_SPECIAL_BASE + 0x11)
#define KB_KC_LCTRL (KB_KC_SPECIAL_BASE + 0x12)
#define KB_KC_SHIFT_ALT_LEFT (KB_KC_SPECIAL_BASE + 0x13)
#define KB_KC_SHIFT_ALT_RIGHT (KB_KC_SPECIAL_BASE + 0x14)
#define KB_KC_KEYPAD KB_KC_NULL
#define KB_KC_LALT KB_KC_NULL
#define KB_KC_CAPSLOCK KB_KC_NULL
#define KB_KC_F(i) KB_KC_NULL


#ifdef __KERNEL__

    void kb_process_byte(uint8_t b);

#endif
